function r2(v){return v!=null?Math.round(v*100)/100:null}
function calcRSI(c,p=14){if(!c||c.length<p+1)return 50;let g=0,l=0;for(let i=c.length-p;i<c.length;i++){const d=c[i]-c[i-1];if(d>0)g+=d;else l-=d}const rs=g/(l||.001);return r2(100-100/(1+rs))}
function calcBB(c,p=20){if(!c||c.length<p)return{pos:.5};const s=c.slice(-p),m=s.reduce((a,b)=>a+b,0)/p,std=Math.sqrt(s.reduce((a,b)=>a+(b-m)**2,0)/p),u=m+2*std,l=m-2*std,last=c[c.length-1];return{pos:std>0?r2((last-l)/(u-l)):.5}}
function tech(nk){const base=nk.price,prev=nk.prevClose,c=[...(nk.closes||[]),base],rsi=calcRSI(c),bb=calcBB(c),day=(base-prev)/prev*100,rec=nk.dayLow?(base-nk.dayLow)/(nk.open-nk.dayLow+.001):.3,sc=(rsi>70?-.55:rsi<40?.2:(55-rsi)/100)+(bb.pos>.85?-.25:bb.pos<.15?.3:(0.5-bb.pos)*.3)+(day<-1.5?.1:day>1.5?-.1:0)+rec*.15,sig=base*0.0042,cl=r2(base+sc*sig*2.8+(Math.random()-.5)*sig*.3);return{close:cl,confidence:r2(Math.min(75,58+(nk.closes||[]).length*.8)),signal:cl>base?"上昇":cl<base?"下落":"横ばい",reason:`RSI=${rsi.toFixed(1)}・BB位置=${(bb.pos*100).toFixed(1)}%・日中=${day.toFixed(2)}%・戻し=${(rec*100).toFixed(1)}%。スコア=${sc.toFixed(4)}`}}
function fund(nk,macro){const base=nk.price,per=23.2,eps=r2(base/per),fv=r2(eps*21.5),dev=(base-fv)/fv,nas=(macro?.nasdaq?.changePct||0)/100*.28,sc=-dev*.45+.012+nas,sig=base*.003,cl=r2(base+sc*sig*2.5+(Math.random()-.5)*sig*.3);return{close:cl,confidence:62.5,signal:cl>base?"上昇":cl<base?"下落":"横ばい",reason:`理論値=${fv.toLocaleString()}円(乖離${(dev*100).toFixed(2)}%)・NASDAQ連動${(nas*100).toFixed(3)}%`}}
function sent(nk,macro){const base=nk.price,vix=macro?.vix?.price||16,sp=(macro?.sp500?.changePct||0)/100*.52,nas=(macro?.nasdaq?.changePct||0)/100*.32,ve=vix<15?.18:vix<20?0:vix<25?-.22:-.5,pd=Math.abs(nk.changePct||0)>1.5?-(nk.changePct||0)/100*.25:0,sc=ve+sp+nas+pd,sig=base*.0048,cl=r2(base+sc*sig*2.2+(Math.random()-.5)*sig*.3);return{close:cl,confidence:r2(58+(macro?.sp500?5:0)+(macro?.vix?3:0)),signal:cl>base?"上昇":cl<base?"下落":"横ばい",reason:`VIX=${vix.toFixed(2)}・SP500=${(macro?.sp500?.changePct||0).toFixed(2)}%・NASDAQ=${(macro?.nasdaq?.changePct||0).toFixed(2)}%・スコア=${sc.toFixed(4)}`}}
function mac(nk,macro){const base=nk.price,fx=macro?.usdjpy?.price||147,r10=macro?.us10y?.price||4.35,oil=macro?.crude?.price||68,fi=(fx-150)*100/base,ri=(r10-4)*-.08,oi=(oil-70)*-.0015,sc=fi+ri+oi,sig=base*.0052,cl=r2(base+sc*sig*2+(Math.random()-.5)*sig*.3);return{close:cl,confidence:r2(55+(macro?.usdjpy?4:0)+(macro?.us10y?3:0)),signal:cl>base?"上昇":cl<base?"下落":"横ばい",reason:`ドル円=${fx.toFixed(2)}(${(fi*base).toFixed(0)}円)・米10年=${r10.toFixed(2)}%(${(ri*base).toFixed(0)}円)・原油=$${oil.toFixed(1)}(${(oi*base).toFixed(0)}円)`}}
function dl(nk,macro){const base=nk.price,prev=nk.prevClose,day=(base-prev)/prev*100,dow=new Date().getDay(),de=[0,.05,.02,-.01,-.03,.04][dow]||0,mr=-day*.38,mom=(()=>{const c=nk.closes||[];if(c.length<3)return 0;const l=c.slice(-3);return(l[2]-l[0])/l[0]*100*.22})(),us=(macro?.sp500?.changePct||0)/100*.45,sc=mr/100+mom/100+de/100+us,sig=base*.004,cl=r2(base+sc*base+(Math.random()-.5)*sig*.4);return{close:cl,confidence:r2(65+((nk.closes||[]).length>=10?5:0)+(macro?.sp500?3:0)),signal:cl>base?"上昇":cl<base?"下落":"横ばい",reason:`平均回帰=${mr.toFixed(2)}%・モメンタム=${mom.toFixed(2)}%・曜日効果(${["日","月","火","水","木","金","土"][dow]})=${de.toFixed(2)}%・米連動=${(us*100).toFixed(2)}%`}}
function ens(models){const W={technical:.28,fundamental:.18,sentiment:.20,macro:.14,deeplearning:.20};const e=r2(Object.entries(W).reduce((s,[k,w])=>s+(models[k]?.close||0)*w,0));const cls=Object.values(models).map(m=>m?.close||e);const v=cls.reduce((s,c)=>s+(c-e)**2,0)/cls.length,sg=Math.sqrt(v);return{close:e,high:r2(e+1.96*sg),low:r2(e-1.96*sg),sigma:r2(sg),confidence:r2(Math.min(80,Object.entries(W).reduce((s,[k,w])=>s+(models[k]?.confidence||60)*w,0)))}}
export default async function handler(req,res){
  res.setHeader("Access-Control-Allow-Origin","*");
  res.setHeader("Access-Control-Allow-Methods","POST,OPTIONS");
  if(req.method==="OPTIONS")return res.status(200).end();
  if(req.method!=="POST")return res.status(405).json({error:"POST only"});
  let body=req.body;
  if(typeof body==="string"){try{body=JSON.parse(body)}catch(e){return res.status(400).json({error:"invalid json"})}}
  const{marketData}=body||{};
  if(!marketData?.nikkei?.price)return res.status(400).json({error:"nikkei price required"});
  const nk=marketData.nikkei,macro=marketData;
  const models={technical:tech(nk),fundamental:fund(nk,macro),sentiment:sent(nk,macro),macro:mac(nk,macro),deeplearning:dl(nk,macro)};
  const e=ens(models);
  const base=nk.price,prev=nk.prevClose;
  return res.status(200).json({ok:true,input:{current:base,prevClose:prev,open:nk.open,dayHigh:nk.dayHigh,dayLow:nk.dayLow,changePct:nk.changePct,name:nk.name},models,ensemble:{...e,diffFromCurrent:r2(e.close-base),diffFromPrev:r2(e.close-prev),diffPct:r2((e.close-prev)/prev*100),summary:`現在値${base.toLocaleString("ja-JP",{minimumFractionDigits:2})}円から5モデルアンサンブル予測。予測終値${e.close.toLocaleString("ja-JP",{minimumFractionDigits:2})}円（95%CI:${e.low.toLocaleString("ja-JP",{minimumFractionDigits:2})}〜${e.high.toLocaleString("ja-JP",{minimumFractionDigits:2})}円）。`},macro:{usdjpy:macro.usdjpy?.price,vix:macro.vix?.price,us10y:macro.us10y?.price,sp500:macro.sp500,nasdaq:macro.nasdaq,crude:macro.crude,oil:macro.crude?.price},predictedAt:new Date().toISOString()});
}
